name: fancy_snackbar
description: A new Flutter package project.
version: 0.0.2
homepage: https://github.com/MR0100/fancy_snackbar.git

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/video/
